[package]
name = "gen_terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
noise = "0.7.0"
bevy = { git = "https://github.com/bevyengine/bevy", rev ="26c3b20f1ce1e04fcd37816d35fdff4d8433064f"}

[dev-dependencies]
proptest = "1.0"